#!/usr/bin/env bash
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School for the win!" > /var/www/html/index.html
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=IBbwpEZhXkM;'/etc/nginx/sites-available/default
sudo service nginx restart
