#!/usr/bin/env bash
# HTTP response
# custom header (on web-01 and web-02)
# -The name X-Served-By
# -The value hostname
# server Nginx is running on
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.html
FILE="/etc/nginx/sites-available/default"
sudo sed -i "22i \\\tadd_header X-Served-By $HOSTNAME;" $FILE
sudo service nginx start
