#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 serve
sudo apt-get -y update
sudo apt-get install -y haproxy=1.6\*
FILE=/etc/haproxy/haproxy.cfg
echo "listen 1642-lb-01" | sudo tee -a $FILE
echo "bind *:80" | sudo tee -a $FILE
echo "mode http" | sudo tee -a $FILE
echo "balance roundrobin" | sudo tee -a $FILE
echo "server 1642-web-01 35.237.101.138 check" | sudo tee -a $FILE
echo "server 1642-web-02 34.75.125.6 check" | sudo tee -a $FILE
sudo service haproxy restart
