#!/usr/bin/env bash
# Script that verify that  a file exist
file_name=holbertonschool
if [ -e "$STR" ]
then
	echo "$file_name file exists"
	if [ -s "$file_name" ]
	then
		echo "$file_name file is not empty"
	else
		echo "$file_name file is empty"
	fi

if [ -f "$file_name" ]
then
	echo "$file_name is a regular file"
else
	echo "$file_name file does not exist"
fi
